### ISSUE TITLE
Upload to JIRA

### ISSUE THREAD

**Issue by raphaelhagi** [fod-dev/FoDBugTrackerUtility#30]
Hello,

I have two problems to solve, please help.

1) I need to submit my vulnerabilities to JIRA, but everytime I ran the bugtracker plugin it adds all vulnerabilityes to backlog again, and don't mark my issues as sent to external bugtracker, how can I fix it?

2) When my development team fix some issue, my CI/CD will run the SCA again. When some vulnerabity has fixed, can the plugin add some description on previous ticket opened on JIRA?

Thank you.

**Comment by rsenden** [comment]
Hi,

As you mention SCA, I'm assuming you are integrating with SSC (not FoD), correct? 

In order to allow the utility to store the links to JIRA in SSC, you will need to configure either the bugLinkCustomTagName or the addNativeBugLink on the SSCSourceVulnerabilitiesConfiguration bean in the configuration file. Please see the documentation for more details. 

Without one of these properties enabled, the utility won't keep track of which vulnerabilities have already been submitted to the bug tracker, and thus re-submit them on every run. I'll look into having the utility output a warning message if neither of these properties have been configured.

Storing the bug link in SSC is also a prerequisite for bug state management, which allows for updating JIRA issues based on current vulnerability state. For example, you can have the utility automatically add a comment and close JIRA issues once the vulnerabilities have been removed (fixed) in SSC. Please see the documentation (Configuration->Target->Jira) for the transitionsForOpeningIssue and transitionsForClosingIssue properties.

Note that the utility does not explicitly support adding a comment only, without transitioning the Jira issue to a different state (i.e. closing the issues). If you would like to see this functionality, please raise a feature request.
